# Generated by Django 4.2.25 on 2026-09-22 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About PandesalHub', max_length=150)),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kakanin_aboutpage',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gcash_number', models.CharField(blank=True, help_text='GCash account number for payments', max_length=20)),
                ('map_link', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact info',
                'db_table': 'kakanin_contactinfo',
            },
        ),
        migrations.CreateModel(
            name='Kakanin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kakanin_images/')),
                ('categories', models.JSONField(blank=True, default=list, help_text='Categories of kakanin (can select multiple)')),
                ('is_available', models.BooleanField(default=True, help_text='Is this product currently available?')),
                ('available_days', models.JSONField(blank=True, default=list, help_text='Days of the week when available')),
                ('available_from_time', models.TimeField(blank=True, help_text='Available from this time', null=True)),
                ('available_to_time', models.TimeField(blank=True, help_text='Available until this time', null=True)),
                ('preparation_time_hours', models.PositiveIntegerField(default=0, help_text='Hours needed to prepare this item')),
                ('preparation_days', models.PositiveIntegerField(default=3, help_text='Days needed to prepare this item (e.g., 2, 3, 5 days)')),
                ('max_daily_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity available per day', null=True)),
                ('allow_order_now', models.BooleanField(default=True)),
                ('allow_reservation', models.BooleanField(default=True)),
                ('min_order_quantity', models.PositiveIntegerField(default=1)),
                ('delivery_min_quantity', models.PositiveIntegerField(default=20)),
                ('preorder_downpayment_percent', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('reservation_downpayment_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available pieces in stock')),
                ('available_today', models.BooleanField(default=False, help_text='Available for order today')),
            ],
            options={
                'db_table': 'kakanin_kakanin',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('ready_for_pickup', 'Ready for Pickup'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('downpayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('gcash', 'GCash'), ('cash', 'Cash on Pickup')], default='cash', max_length=20)),
                ('gcash_reference', models.CharField(blank=True, help_text='GCash reference number', max_length=100)),
                ('payment_proof', models.ImageField(blank=True, help_text='Payment screenshot', null=True, upload_to='payment_proofs/')),
                ('delivery', models.BooleanField(default=False, help_text='True for delivery, False for pickup')),
                ('notes', models.TextField(blank=True, help_text='Customer notes or special requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kakanin_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preparation_days', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kakanin_images/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kakanin_product',
            },
        ),
        migrations.CreateModel(
            name='ReservationCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kakanin_reservationcart',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('barangay', models.CharField(blank=True, choices=[('agpangi', 'Agpangi'), ('anislagan', 'Anislagan'), ('atipolo', 'Atipolo'), ('borac', 'Borac'), ('cabungaan', 'Cabungaan'), ('calumpang', 'Calumpang'), ('capiñahan', 'Capiñahan'), ('caraycaray', 'Caraycaray'), ('catmon', 'Catmon'), ('haguikhikan', 'Haguikhikan'), ('imelda', 'Imelda'), ('larrazabal', 'Larrazabal'), ('libtong', 'Libtong'), ('libertad', 'Libertad'), ('lico', 'Lico'), ('lucsoon', 'Lucsoon'), ('mabini', 'Mabini'), ('padre_inocentes_garcia', 'Padre Inocentes Garcia (Pob.)'), ('padre_sergio_eamiguel', 'Padre Sergio Eamiguel'), ('sabang', 'Sabang'), ('san_pablo', 'San Pablo'), ('santo_nino', 'Santo Niño'), ('santissimo_rosario', 'Santissimo Rosario Pob. (Santo Rosa)'), ('talustusan', 'Talustusan'), ('villa_caneja', 'Villa Caneja'), ('villa_consuelo', 'Villa Consuelo')], help_text='Barangay in Naval, Biliran', max_length=50)),
                ('zone', models.CharField(blank=True, help_text='Zone/Purok number', max_length=50)),
                ('additional_notes', models.TextField(blank=True, help_text='Nearest landmark or additional directions')),
                ('address', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kakanin_userprofile',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('downpayment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('delivery', models.BooleanField(default=False, help_text='True for delivery, False for pickup')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending_payment', max_length=30)),
                ('payment_method', models.CharField(choices=[('gcash', 'GCash')], default='gcash', max_length=30)),
                ('gcash_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='reservations/')),
                ('notes', models.TextField(blank=True, help_text='Customer notes or special requests')),
                ('decision_notes', models.TextField(blank=True, help_text='Admin decision notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='pandesal.kakanin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kakanin_reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Product quality rating (1-5 stars)')),
                ('product_comment', models.TextField(blank=True, help_text='Comments about the product quality')),
                ('service_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Service rating (1-5 stars)')),
                ('service_comment', models.TextField(blank=True, help_text='Comments about the service')),
                ('delivery_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Delivery service rating (1-5 stars)', null=True)),
                ('delivery_comment', models.TextField(blank=True, help_text='Comments about delivery (timeliness, condition, etc.)')),
                ('pickup_speed_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Pickup confirmation speed (1-5 stars)', null=True)),
                ('overall_comment', models.TextField(blank=True, help_text='Overall experience and suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='pandesal.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kakanin_rating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(help_text='Payment reference number', max_length=100)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='pandesal.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kakanin_payment',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at time of order', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='quantity * price', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pandesal.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandesal.kakanin')),
            ],
            options={
                'db_table': 'kakanin_orderitem',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('low_stock', 'Low Stock'), ('order_submitted', 'Order Submitted'), ('payment_pending', 'Payment Pending'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('order_confirmed', 'Order Confirmed'), ('ready_for_pickup', 'Ready for Pickup'), ('out_for_delivery', 'Out for Delivery'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('reservation_submitted', 'Reservation Submitted'), ('reservation_pending_payment', 'Reservation Pending Payment'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_completed', 'Reservation Completed'), ('feedback', 'Feedback Received')], max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, help_text='Related order if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pandesal.order')),
                ('reservation', models.ForeignKey(blank=True, help_text='Related reservation if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pandesal.reservation')),
                ('user', models.ForeignKey(blank=True, help_text='User to notify (null for admin notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kakanin_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Optional image attachment', null=True, upload_to='message_images/')),
                ('guest_name', models.CharField(blank=True, max_length=150)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('unsent_for_sender', models.BooleanField(default=False)),
                ('unsent_for_recipient', models.BooleanField(default=False)),
                ('unsent_for_everyone', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='pandesal.message')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kakanin_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=150)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kakanin_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pandesal.reservationcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandesal.kakanin')),
            ],
            options={
                'db_table': 'kakanin_reservationcartitem',

                'unique_together': {('cart', 'product', 'reservation_date', 'reservation_time')},
            },
        ),
    ]
