# Generated by Django 4.2.25 on 2026-09-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandesal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aboutpage',
            table='pandesal_aboutpage',
        ),
        migrations.AlterModelTable(
            name='contactinfo',
            table='pandesal_contactinfo',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='pandesal_feedback',
        ),
        migrations.AlterModelTable(
            name='kakanin',
            table='pandesal_kakanin',
        ),
        migrations.AlterModelTable(
            name='message',
            table='pandesal_message',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='pandesal_notification',
        ),
        migrations.AlterModelTable(
            name='order',
            table='pandesal_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='pandesal_orderitem',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='pandesal_payment',
        ),
        migrations.AlterModelTable(
            name='product',
            table='pandesal_product',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='pandesal_rating',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='pandesal_reservation',
        ),
        migrations.AlterModelTable(
            name='reservationcart',
            table='pandesal_reservationcart',
        ),
        migrations.AlterModelTable(
            name='reservationcartitem',
            table='pandesal_reservationcartitem',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='pandesal_userprofile',
        ),
    ]
