# Generated by Django 4.2.25 on 2026-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandesal', '0002_order_seller_pandesal_seller_rating_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandesal',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Where customers can buy / pick up this pandesal (e.g. Zone 2, Brgy. Caraycaray, Naval, Biliran)', max_length=255),
        ),
    ]
