# Generated by Django 4.2.25 on 2026-09-24 01:18

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('pandesal', '0002_alter_aboutpage_table_alter_contactinfo_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kakanin',
            new_name='Pandesal',
        ),
        migrations.AlterModelTable(
            name='pandesal',
            table='pandesal_pandesal',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pandesal_images/'),
        ),
    ]
