# Generated by Django 4.2.25 on 2026-09-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandesal', '0003_pandesal_alter_product_image_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandesal',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Categories of pandesal (can select multiple)'),
        ),
        migrations.AlterField(
            model_name='pandesal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pandesal_images/'),
        ),
    ]
