# Generated by Django 4.2.25 on 2026-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandesal', '0003_pandesal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Customer delivery address', null=True),
        ),
    ]
